# Generated by Django 3.2.18 on 2023-03-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softechapp', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='softechapp.myuser'),
        ),
    ]
