# Generated by Django 4.1.7 on 2023-03-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softechapp', '0003_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='User',
        ),
    ]
