# Generated by Django 4.1.7 on 2023-03-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softechapp', '0006_rename_user_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
