# Generated by Django 4.1.7 on 2023-03-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softechapp', '0007_remove_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('likes', models.ManyToManyField(related_name='post_likes', to='softechapp.myuser')),
            ],
        ),
    ]
