# Generated by Django 4.1.7 on 2023-03-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softechapp', '0008_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likes',
        ),
    ]
